import "./globals.css";
import Header from "@/shared/header/header";
import Footer from "@/shared/footer/footer";
import { Barlow } from "next/font/google";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Pradeep K. | UI Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${barlow.className}`}>
        <div className="bgbody"></div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
